export async function createManagementAccess(reference) {
  const token = Array.from(crypto.getRandomValues(new Uint8Array(32)), byte => byte.toString(16).padStart(2, "0")).join("");
  const hash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(token));
  const managementTokenHash = Array.from(new Uint8Array(hash), byte => byte.toString(16).padStart(2, "0")).join("");
  const base = window.location.hostname === "ceaserh.github.io" ? "/vallejo-tech/" : "/";
  // Fragment keeps the private token out of HTTP requests and referrer headers.
  return { managementTokenHash, managementUrl: `${window.location.origin}${base}#appointment=${reference}&token=${token}` };
}

export function managementEmailFooter(data) {
  if (!data.managementUrl) return "";
  // URLs are generated by this app; escape attribute delimiters defensively.
  const url = data.managementUrl.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
  const reference = String(data.reference || data.id || "").replace(/[<>&"']/g, "");
  return `<div style="margin:24px 0 0;font-family:Arial,sans-serif;text-align:left;">
    <table role="presentation" cellspacing="0" cellpadding="0" border="0"><tr><td align="center" bgcolor="#2563eb" style="border-radius:6px;">
      <a href="${url}" style="display:inline-block;padding:11px 18px;border:1px solid #2563eb;border-radius:6px;background:#2563eb;color:#ffffff;text-decoration:none;font-size:14px;font-weight:bold;line-height:20px;">Manage appointment</a>
    </td></tr></table>
    <p style="margin:10px 0 0;color:#aeb8c7;font-size:12px;line-height:18px;">View or cancel your appointment online.</p>
    <p style="margin:16px 0 0;color:#aeb8c7;font-size:12px;line-height:18px;word-break:break-all;">Appointment reference: ${reference}</p>
    <p style="margin:4px 0 0;color:#8792a3;font-size:11px;line-height:17px;">Keep this link private. Anyone with it can view or cancel your appointment.</p>
  </div>`;
}

export function insertManagementAction(html, data) {
  const action = managementEmailFooter(data);
  if (html.includes("<!-- appointment-management -->")) {
    return html.replace("<!-- appointment-management -->", () => action);
  }
  // Existing Firestore confirmation template: place the action after the details
  // and before the next-steps paragraph, inside the card's padded content area.
  const nextSteps = /<p\b[^>]*>\s*We will review the details/i;
  if (nextSteps.test(html)) return html.replace(nextSteps, match => action + match);
  if (/<\/body>/i.test(html)) return html.replace(/<\/body>/i, match => action + match);
  return html + action;
}
